networks:
  default:

volumes:
  images:
  logs:

services:
  app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - images:/app/images
      - logs:/app/logs
    networks:
      - default

  nginx:
    container_name: nginx-app
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - images:/images
      - ./app/static:/etc/nginx/html
      - ./favicon.ico:/images/favicon.ico
    networks:
      - default
    depends_on:
      - app